name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  Tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Lint
        run: ./gradlew lintDebug
      - name: Run Ktlint
        run: ./gradlew ktlintCheck

      - name: Run build debug
        run: ./gradlew assembleDebug
      - name: Run Tests
        run: ./gradlew :Provider:testDebugUnitTest --stacktrace
      - name: Run build release
        run: ./gradlew assembleRelease
