name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  Tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run check
        run: ./gradlew check --no-daemon --stacktrace
