name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  Tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    resources:
        cpu: 2 # Adjust the number of CPU cores as needed
        memory: 4GB # Adjust the memory size as needed
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Lint
        run: ./gradlew lintDebug
      - name: Run Ktlint
        run: ./gradlew ktlintCheck

      - name: Run build debug
        run: ./gradlew assembleDebug
      - name: Run Tests
        run: ./gradlew :Provider:testDebugUnitTest --no-daemon --stacktrace
      - name: Run build release
        run: ./gradlew assembleRelease
