name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Release Spotify Confidence Provider
    runs-on: ubuntu-latest

    steps:
      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/checkout@v1

      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12

      - name: Grant Permission for Gradlew to Execute
        run: chmod +x gradlew

      - name: Build AAR ⚙️🛠
        run: bash ./gradlew :provider:assemble

      - name: Create Release ✅
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_PUBLISH }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload Confidence Provider AAR 🗳
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_PUBLISH }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Provider/build/outputs/aar/Provider-release.aar
          asset_name: provider-release.aar
          asset_content_type: application/aar